In [1]:

import pandas as pd
file_path = (
    "dataset_2026-08-22T18_36_56.791903119Z_"
    "DEFAULT_INTEGRATION_SSSU_DF_SCIENTIFIC_RESEARCH_"
    "DEVELOPMENT_LATEST.csv"
)

df = pd.read_csv(file_path)

print("Дані успішно завантажено!")
print("Кількість рядків:", df.shape[0])
print("Кількість колонок:", df.shape[1])

display(df.head())

Дані успішно завантажено!
Кількість рядків: 136
Кількість колонок: 22

,Показник,Територіальний розріз,Категорія розрізу,Вид економічної діяльності,Періодичність,Одиниця виміру,Масштабування,Кількість десяткових знаків,Спеціальне значення даних,Примітки набору даних,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Витрати на наукові дослідження і розробки,Україна,Види витрат,Усього,Річна,Гривня,Тисячі,Один,NaN,1. Розрахунок показників темпів зростання/зниж...,...,NaN,NaN,NaN,NaN,NaN,20973775.2,17117836.2,21348062.6,28328170.6,NaN
1,Витрати на наукові дослідження і розробки,Україна,Галузі наук,Усього,Річна,Гривня,Тисячі,Один,NaN,1. Розрахунок показників темпів зростання/зниж...,...,NaN,NaN,NaN,17254629.7,17022419.3,20973775.2,17117836.2,21348062.6,28328170.6,NaN
2,Витрати на наукові дослідження і розробки,Україна,Джерела фінансування,Усього,Річна,Гривня,Тисячі,Один,Конфіденційна статистична інформація,1. Розрахунок показників темпів зростання/зниж...,...,NaN,NaN,NaN,17254629.7,17022419.3,NaN,17117836.2,21348062.6,28328170.6,NaN
3,Витрати на наукові дослідження і розробки,Україна,Види досліджень і розробок,Усього,Річна,Гривня,Тисячі,Один,NaN,1. Розрахунок показників темпів зростання/зниж...,...,NaN,13379292.4,16773724.5,17254629.7,17022419.3,20973775.2,17117836.2,21348062.6,28328170.6,NaN
4,Витрати на наукові дослідження і розробки,Вінницька,Види досліджень і розробок,Усього,Річна,Гривня,Тисячі,Один,NaN,1. Розрахунок показників темпів зростання/зниж...,...,NaN,NaN,NaN,39618.3,50756.2,NaN,NaN,NaN,NaN,NaN

In [2]:
print("Назви колонок:\n")

for col in df.columns:
    print(col)

print("\nТипи даних:")
print(df.dtypes)

Назви колонок:

Показник
Територіальний розріз
Категорія розрізу
Вид економічної діяльності
Періодичність
Одиниця виміру
Масштабування
Кількість десяткових знаків
Спеціальне значення даних
Примітки набору даних
Примітки часового ряду
Примітки спостереження
2016
2017
2018
2019
2020
2021
2022
2023
2024
2025

Типи даних:
Показник                        object
Територіальний розріз           object
Категорія розрізу               object
Вид економічної діяльності      object
Періодичність                   object
Одиниця виміру                  object
Масштабування                   object
Кількість десяткових знаків     object
Спеціальне значення даних       object
Примітки набору даних           object
Примітки часового ряду         float64
Примітки спостереження          object
2016                           float64
2017                           float64
2018                           float64
2019                           float64
2020                           float64
2021                           float64
2022                           float64
2023                           float64
2024                           float64
2025                           float64
dtype: object

In [3]:
missing_values = df.isna().sum()

print("Пропущені значення:")
print(missing_values)

Пропущені значення:
Показник                         0
Територіальний розріз            0
Категорія розрізу                0
Вид економічної діяльності       0
Періодичність                    0
Одиниця виміру                   0
Масштабування                    0
Кількість десяткових знаків      0
Спеціальне значення даних      113
Примітки набору даних            0
Примітки часового ряду         136
Примітки спостереження         107
2016                           111
2017                           109
2018                           109
2019                            32
2020                            40
2021                            40
2022                            47
2023                            50
2024                            43
2025                           113
dtype: int64

In [4]:
print(
    missing_values[missing_values > 0]
    .sort_values(ascending=False)
)

Примітки часового ряду       136
Спеціальне значення даних    113
2025                         113
2016                         111
2017                         109
2018                         109
Примітки спостереження       107
2023                          50
2022                          47
2024                          43
2020                          40
2021                          40
2019                          32
dtype: int64

In [5]:
duplicates = df.duplicated().sum()

print("Кількість повних дублікатів:", duplicates)

Кількість повних дублікатів: 0

In [6]:
df = df.drop_duplicates().copy()

In [7]:
empty_columns = df.columns[
    df.isna().all()
].tolist()

print("Повністю порожні колонки:")
print(empty_columns)

Повністю порожні колонки:
['Примітки часового ряду']

In [8]:
df = df.drop(columns=empty_columns)

print("Кількість колонок після видалення:", df.shape[1])

Кількість колонок після видалення: 21

In [9]:
text_columns = df.select_dtypes(
    include=["object", "string"]
).columns

for col in text_columns:
    df[col] = (
        df[col]
        .astype("string")
        .str.strip()
        .str.replace(r"\s+", " ", regex=True)
    )

print("Текстові колонки очищено.")

Текстові колонки очищено.

In [10]:
df[text_columns] = df[text_columns].replace(
    {
        "": pd.NA,
        "NULL": pd.NA,
        "null": pd.NA,
        "N/A": pd.NA,
        "NA": pd.NA
    }
)

In [11]:
year_columns = [
    str(year)
    for year in range(2016, 2026)
    if str(year) in df.columns
]

print("Роки:")
print(year_columns)

Роки:
['2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025']

In [12]:
for col in year_columns:
    df[col] = pd.to_numeric(
        df[col],
        errors="coerce"
    )

print(df[year_columns].dtypes)

2016    float64
2017    float64
2018    float64
2019    float64
2020    float64
2021    float64
2022    float64
2023    float64
2024    float64
2025    float64
dtype: object

In [13]:
print(
    df["Спеціальне значення даних"]
    .value_counts(dropna=False)
)

Спеціальне значення даних
<NA>                                    113
Конфіденційна статистична інформація     23
Name: count, dtype: Int64

In [15]:
print("========== РЕЗУЛЬТАТ ОЧИЩЕННЯ ==========")

print("Кількість рядків:", df.shape[0])
print("Кількість колонок:", df.shape[1])
print("Дублікатів:", df.duplicated().sum())

print("\nПропущені значення:")
print(
    df.isna()
    .sum()
    .sort_values(ascending=False)
)

display(df.head())
print(df.shape)

========== РЕЗУЛЬТАТ ОЧИЩЕННЯ ==========
Кількість рядків: 136
Кількість колонок: 21
Дублікатів: 0

Пропущені значення:
2025                           113
Спеціальне значення даних      113
2016                           111
2018                           109
2017                           109
Примітки спостереження         107
2023                            50
2022                            47
2024                            43
2020                            40
2021                            40
2019                            32
Масштабування                    0
Кількість десяткових знаків      0
Одиниця виміру                   0
Примітки набору даних            0
Територіальний розріз            0
Періодичність                    0
Вид економічної діяльності       0
Категорія розрізу                0
Показник                         0
dtype: int64

,Показник,Територіальний розріз,Категорія розрізу,Вид економічної діяльності,Періодичність,Одиниця виміру,Масштабування,Кількість десяткових знаків,Спеціальне значення даних,Примітки набору даних,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Витрати на наукові дослідження і розробки,Україна,Види витрат,Усього,Річна,Гривня,Тисячі,Один,<NA>,1. Розрахунок показників темпів зростання/зниж...,...,NaN,NaN,NaN,NaN,NaN,20973775.2,17117836.2,21348062.6,28328170.6,NaN
1,Витрати на наукові дослідження і розробки,Україна,Галузі наук,Усього,Річна,Гривня,Тисячі,Один,<NA>,1. Розрахунок показників темпів зростання/зниж...,...,NaN,NaN,NaN,17254629.7,17022419.3,20973775.2,17117836.2,21348062.6,28328170.6,NaN
2,Витрати на наукові дослідження і розробки,Україна,Джерела фінансування,Усього,Річна,Гривня,Тисячі,Один,Конфіденційна статистична інформація,1. Розрахунок показників темпів зростання/зниж...,...,NaN,NaN,NaN,17254629.7,17022419.3,NaN,17117836.2,21348062.6,28328170.6,NaN
3,Витрати на наукові дослідження і розробки,Україна,Види досліджень і розробок,Усього,Річна,Гривня,Тисячі,Один,<NA>,1. Розрахунок показників темпів зростання/зниж...,...,NaN,13379292.4,16773724.5,17254629.7,17022419.3,20973775.2,17117836.2,21348062.6,28328170.6,NaN
4,Витрати на наукові дослідження і розробки,Вінницька,Види досліджень і розробок,Усього,Річна,Гривня,Тисячі,Один,<NA>,1. Розрахунок показників темпів зростання/зниж...,...,NaN,NaN,NaN,39618.3,50756.2,NaN,NaN,NaN,NaN,NaN

(136, 21)

In [16]:
output_file = "cleaned_research_expenses.csv"

df.to_csv(
    output_file,
    index=False,
    encoding="utf-8-sig"
)

print("Очищення завершено!")
print("Файл збережено як:")
print(output_file)

Очищення завершено!
Файл збережено як:
cleaned_research_expenses.csv